### ISSUE TITLE
rsync: -aX: unknown option

### ISSUE THREAD

**Issue by canalnoises** [ryangball/package-jamf-pro#1]
When I try to run this script I get errors saying -aX is an unknown option for rsync. The script outputs this for each application it's trying to package:

`Staging Jamf Admin.app for packaging...`
`rsync: -aX: unknown option`
`rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(1337) [client=2.6.9]`
`chown: /private/tmp/jamfpro/Jamf Admin/files/Jamf Pro: No such file or directory`
`Setting permissions to restrict non-admin users from reading and executing Jamf Admin.app.`
`chmod: /private/tmp/jamfpro/Jamf Admin/files/Jamf Pro: No such file or directory`
`Packaging com.jamfsoftware.JamfAdmin version 10.11.1...`
`pkgbuild: error: Component path "/private/tmp/jamfpro/Jamf Admin/files/Jamf Pro/Jamf Admin.app" does not exist.`

Running macOS 10.14.5, rsync 2.6.9

**Comment by ryangball** [comment]
Please clone the latest update to the repo and try it again. The X flag is used to preserve extended attributes in newer versions of rsync. In older versions of rsync (what is shipped with macOS), an E is used instead. Let me know if this works for you.

**Comment by canalnoises** [comment]
Looks like it works now. Thanks!
